// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBORqlDA-wqsoxbcucCGLPGU0oYc2CpBl8',
    appId: '1:256921340066:android:92ee43cce4ddfc70876ffb',
    messagingSenderId: '256921340066',
    projectId: 'apprabbitdev',
    storageBucket: 'apprabbitdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU23y2xVSfHqJMX22VEiIvShrx75Dm3EQ',
    appId: '1:256921340066:ios:edc1db9671ddba15876ffb',
    messagingSenderId: '256921340066',
    projectId: 'apprabbitdev',
    storageBucket: 'apprabbitdev.appspot.com',
    androidClientId: '256921340066-icu10lm2nfmc32tgrmg3bp0ll6a1rbhi.apps.googleusercontent.com',
    iosClientId: '256921340066-g13pjcvehq17pnfe739a2jj3oi8e2rlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstGradeLuggage',
  );
}
